name: PostgreSQL
description: |
  Host a PostgreSQL server

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-04-04"


environment_variables:
  DATABASE_NAME:
    default: "sample"
    description: "Enter preferred collection name for Postgres DB to store document embeddings in."
    required: false

  POSTGRES_USER:
    default: "admin"
    description: "username for PostgreSQL. Required only if POSTGRES_AUTH is true"
    required: true

  POSTGRES_PASSWORD:
    default: "admin"
    description: "Password for POSTGRES_USER. Required only if POSTGRES_AUTH is true"
    required: true

  POSTGRES_LOG_LEVEL:
    default: "INFO"
    description: "PostgreSQL server log level."
    required: false


runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.11
    edition: Standard PG

tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_install_dependencies/vm_install_dependencies.py
    short_summary: Install PostgreSQL Dependencies
    kernel: python3
    cpu: 2
    memory: 8
    
  - type: run_session
    name: Setup and Configure Postgres Server
    script: 1_configure_postgres/configure_postgres.py
    short_summary: Setup Postgres Server Vector DB
    long_summary: Resolve sqlite dependency with python version and control logging in Postgres server package
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: PostgreSQL Server
    subdomain: cml-postgres-server
    script: 2_start_postgres/vm_start_server.py
    short_summary: Start PostgreSQL Server
    long_summary: Start PostgreSQL Server. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
